name: Release
on:
  push:
    branches: ['main']
    paths-ignore:
      - 'README.md'
      - '*.md'
      - '.github/ISSUE_TEMPLATE/*'
      - '.github/assets/*'
      - '.github/*'
      - '*.md'
jobs:
  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install electron-builder
        run: npm i electron-builder -g

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: npm run publish:linux
  publish_on_win:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install electron-builder
        run: npm i electron-builder -g

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: npm run publish:win
  publish_on_macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install dmg-license
        run: npm i dmg-license

      - name: Install electron-builder
        run: npm i electron-builder -g

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: npm run publish:mac
